config:
  # Configuration values to set up basic communication
  # Set your COM port e.g. COM3 for Windows, /dev/ttyACM0 for Linux...
  # Use AUTO for COM port auto-discovery (may not work on every setup)
  # COM_PORT: "/dev/ttyACM0"
  # COM_PORT: "COM3"
  COM_PORT: COM5

  # Theme to use (located in res/themes)
  # Available themes:
  # - 3.5inchTheme2
  # - Terminal
  # - Landscape6Grid
  # - LandscapeMagicBlue
  # - Cyberpunk
  # - Cyberpunk-net
  # - bash-dark-green
  # - bash-dark-green-gpu
  # - BigClock
  THEME: Cyberdemon

  # Hardware sensors reading
  # Choose the appropriate method for reading your hardware sensors:
  # - PYTHON         use Python libraries (psutils, GPUtil...) to read hardware sensors (supports all OS but not all HW)
  # - LHM            use LibreHardwareMonitor library to read hardware sensors (Windows only - NEEDS ADMIN RIGHTS)
  # - STUB / STATIC  use random/static data instead of real hardware sensors
  # - AUTO           use the best method based on your OS: Windows OS will use LHM, other OS will use Python libraries
  HW_SENSORS: PYTHON

  # Network interfaces
  # Linux/MacOS interfaces are named "eth0", "wlan0", "wlp1s0", "enp2s0"...
  # For Windows use the interfaces pretty name: "Ethernet 2", "Wi-Fi", ...
  # Leave the fields empty if the card does not exist on your setup
  ETH: Ethernet # Ethernet Card
  WLO: Wi-Fi # Wi-Fi Card

display:
  # Display revision: A or B (for "flagship" version, use B) or SIMU for simulated LCD (image written in screencap.png)
  # To identify your revision: https://github.com/mathoudebine/turing-smart-screen-python/wiki/Hardware-revisions
  REVISION: B

  # Display Brightness
  # Set this as the desired %, 0 being completely dark and 100 being max brightness
  # Warning: revision A display can get hot at high brightness!
  BRIGHTNESS: 100

  # Display reverse: true/false
  # Set to true to reverse display orientation (landscape <-> reverse landscape, portrait <-> reverse portrait)
  # Note: Display basic orientation (portrait or landscape) is defined by the theme you have selected
  DISPLAY_REVERSE: false

  # Display resolution in portrait orientation
  # Do not use this setting to rotate display! The selected theme handles landscape/portrait orientation
  DISPLAY_WIDTH: 320  # Do not change unless you have a good reason
  DISPLAY_HEIGHT: 480  # Do not change unless you have a good reason


